name: Build Images

on: [pull_request]

jobs:
  build-chain-images:
    name: Build Images
    strategy:
      matrix:
        images: ["abcd", "1234"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Chain
        id: build-chain
        uses: kiegroup/github-action-build-chain@BXMSPROD-951
        with:
          build-command: "echo ${{ matrix.images }}"
          workflow-file-name: "pull_request.yml"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
